### ISSUE TITLE
Code is showing error 

### ISSUE THREAD

**Issue by prateek1108** [alexhulbert/Cryogen#5]
hello sir ,
i am working on same kind of thing as you describe in this project, i had downloaded Icew1nd and i m tried to compile your project but it showing error in my system is any framework or environment is required to execute this project.
![error issue](https://cloud.githubusercontent.com/assets/5064077/3596128/2ba6d8a2-0cc0-11e4-8795-26f56880c97a.png)

**Comment by alexhulbert** [comment]
Main.java is just the main class. You're not compiling it correctly. You need to do stuff like import submodules, include libraries, etc.

You _could_ compile Icew1nd manually, but I'd recommend just letting an IDE do everything for you. I used NetBeans to make this, so all you really need to do is open the "Icewind" folder in NetBeans and click the clean&build icon.

**Comment by prateek1108** [comment]
hello sir 
i had tried this project in netbeans but it is also showing error i.e. undecorator project is missing.... how can i overcome this problem
![issue in netbeans](https://cloud.githubusercontent.com/assets/5064077/3623743/1e120b46-0e53-11e4-962f-2594a0422b58.png)

**Comment by PythEch** [comment]
You should do a recursive git clone (git clone --recursive), or just use https://windows.github.com/

Problem is it depends on Undecorator, and it's included as submodule, you can also try [manually downloading it](https://github.com/in-sideFX/Undecorator).

**Comment by alexhulbert** [comment]
Or try `git submodule update`? I might want to add that ta a "build instructions" section.

Also, like @PythEch said, make sure you didn't use the "Download Zip" button. You need to clone (read: download) the repo using the `git clone --recursive https://github.com/Triforce1/Icew1nd.git` command.

**Comment by prateek1108** [comment]
As per your guideline i had cloned the ICEW1ND by using  https://windows.github.com/ , but now code is showing errors that is
"\Icewind\nbproject\build-impl.xml:902:The following error occurred while executing this line:" 
"\Icewind\nbproject\build-impl.xml:1432: The following error occurred while executing this line:"
"Icew1nd\lib\Undecorator\nbproject\jfx-impl.xml:1037: The following error occurred while executing this line:"
"Icew1nd\lib\Undecorator\nbproject\jfx-impl.xml:1099: Warning: Could not find resource file "C:\Program Files\Java\jdk1.8.0_11\jre\lib\jfxrt.jar" to copy."

**Comment by alexhulbert** [comment]
Hmmm... It's saying you need JDK8, but I don't think that should be necessary. I'll try pulling the Undecorator submodule to see if that fixes anything.

**Comment by alexhulbert** [comment]
Okay! Try doing `git pull` in the root of the repo (or just click "sync" in Github for Windows). Then build the project again. That should do it.

**Comment by prateek1108** [comment]
thanks a alot for Your precious help now my code is compiled now i run this project and select icloud as the mode and enter the correct id password of icloud then project shows nothing, how can i get the list of backup available on i cloud .

**Comment by alexhulbert** [comment]
Like I said, you can't actually decrypt backups yet. But if you really want to get the most out of Icew1nd so far, read on:

The GUI's not done yet :/. I'm currently focusing on the actual logic for now. If you're feeling a little adventurous, you can try running [iCloudTest.java](https://github.com/Triforce1/Icew1nd/blob/master/Icewind/src/com/alexhulbert/icewind/iCloudTest.java) and breakpointing [line 38](https://github.com/Triforce1/Icew1nd/blob/master/Icewind/src/com/alexhulbert/icewind/iCloudTest.java#L38). You should be able to inspect the "authGet" variable from there.

**Comment by prateek1108** [comment]
Sir , 
For now i want to list and download the backup available on icloud decryption is secondary for me, but as per your guidance i had checked code iCloudTest.java and break point line 38 to check "authGet" variable but in Icew1n project that i had Cloned is not going at that checkpoint, My code does not proceed from Pymobiledevice.java  line no. 83 . its does not return from this function value  pi.exec("from " + location + " import " + module);.Please help me out how can i come out of this issue,

**Comment by prateek1108** [comment]
Sir,
I am Continuously working on Code provided by you but enable to attend my goal (i.e. to list and download the backups stored on icloud), Please to me out to overcome from the error as i discus in above comment in this issue.

**Comment by alexhulbert** [comment]
Would you happen to have a stack trace I could look at? My code seems to be running fine.

**Comment by prateek1108** [comment]
Sorry for late reply, I had attached the print screen of before the error occur after this pi.exec("from " + location + " import " + module); execution the handle does not return to code , so i had send print screen before execution of this line(line no.84 in pymobiledevice.java class)
![error in icewind](https://cloud.githubusercontent.com/assets/5064077/3821970/4c318bb2-1d19-11e4-8348-c63b3c70b94b.png)

**Comment by alexhulbert** [comment]
I don't mean a _call stack_, I mean an _exception's stack trace_. That should appear under the "Output" tab at the bottom **after** line 84 executes. An exception's stack trace should look similar to this:

```
Exception in thread "EXAMPLE" java.lang.NullPointerException
        at com.example.myproject.blah.test(Blah.java:10)
        at com.example.myproject.class.method(Test.java:20)
        at com.example.myproject.main.main(Main.java:30)
        ...
```

**Comment by prateek1108** [comment]
i had copied i complete exception's stack 

```
Detected JavaFX Ant API version 1.3
Launching <fx:jar> task from C:\Program Files\Java\jdk1.8.0_11\jre\..\lib\ant-javafx.jar
Warning: From JDK7u25 the Codebase manifest attribute should be used to restrict JAR repurposing.
         Please set manifest.custom.codebase property to override the current default non-secure value '*'.
Launching <fx:deploy> task from C:\Program Files\Java\jdk1.8.0_11\jre\..\lib\ant-javafx.jar
jfx-deployment-script:
jfx-deployment:
jar:
Copying 31 files to D:\Iphone\icloud code\clone IcewInd\Icew1nd\Icewind\dist\run817901997
jfx-project-debug:
Executing D:\Iphone\icloud code\clone IcewInd\Icew1nd\Icewind\dist\run817901997\Icewind.jar using platform C:\Program Files\Java\jdk1.8.0_11\jre/bin/java
Device "Intel(R) G45/G43 Express Chipset (Microsoft Corporation - WDDM 1.1)" (\\.\DISPLAY1) initialization failed : 
WARNING: bad driver version detected, device disabled. Please update your driver to at least version 8.15.10.2302
Exception in thread "Thread-6" Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "__pyclasspath__/pymobiledevice/lockdown.py", line 24, in <module>
ImportError: No module named usbmux
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1768)
    at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1651)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:204)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3456)
    at javafx.scene.Scene$ClickGenerator.access$8300(Scene.java:3387)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3755)
    at javafx.scene.Scene$MouseHandler.access$1800(Scene.java:3471)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1695)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2486)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:314)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:243)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:345)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:526)
    at com.sun.glass.ui.View.notifyMouse(View.java:898)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.access$300(WinApplication.java:39)
    at com.sun.glass.ui.win.WinApplication$4$1.run(WinApplication.java:112)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1765)
    ... 32 more
Caused by: java.lang.NullPointerException: Location is required.
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3223)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3191)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3164)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3140)
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3120)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3113)
    at com.alexhulbert.icewind.gui.StaticStage.loadScreen(StaticStage.java:65)
    at com.alexhulbert.icewind.gui.AuthenticateController.signIn(AuthenticateController.java:44)
    ... 42 more
Deleting directory D:\Iphone\icloud code\clone IcewInd\Icew1nd\Icewind\dist\run817901997
```

**Comment by alexhulbert** [comment]
Could you tell me if you see a "python" folder in `D:\Iphone\icloud code\clone IcewInd\Icew1nd\Icewind\tmp\pymobiledevice\libs`? If not, try deleting `D:\Iphone\icloud code\clone IcewInd\Icew1nd\Icewind\tmp`. That should get things running smoothly.

**Comment by prateek1108** [comment]
sir  i had fallowed instructions given by you my problem is sort a bit the code is debug after that line but again after few line its again goes in hang position and control doesn't returned to code,

Debug console is showing these lines

Listening on javadebug
User program running
Not able to submit breakpoint LineBreakpoint InvokeLaterDispatcher.java : 106, reason: No executable location available at line 106 in class com.sun.glass.ui.InvokeLaterDispatcher.
Invalid LineBreakpoint InvokeLaterDispatcher.java : 106
LineBreakpoint Main.java : 26 successfully submitted.
Breakpoint hit at line 26 in class com.alexhulbert.icewind.gui.Main by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at Main.java:26.
User program running
LineBreakpoint StaticStage.java : 36 successfully submitted.
LineBreakpoint TitleController.java : 26 successfully submitted.
LineBreakpoint TitleController.java : 22 successfully submitted.
Breakpoint hit at line 22 in class com.alexhulbert.icewind.gui.TitleController by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at TitleController.java:22.
User program running
Not able to submit breakpoint LineBreakpoint RefreshThread.java : 191, reason: No executable location available at line 191 in class com.alexhulbert.icewind.gui.RefreshThread.
Invalid LineBreakpoint RefreshThread.java : 191
Not able to submit breakpoint LineBreakpoint RefreshThread.java : 190, reason: No executable location available at line 190 in class com.alexhulbert.icewind.gui.RefreshThread.
Invalid LineBreakpoint RefreshThread.java : 190
Not able to submit breakpoint LineBreakpoint RefreshThread.java : 189, reason: No executable location available at line 189 in class com.alexhulbert.icewind.gui.RefreshThread.
Invalid LineBreakpoint RefreshThread.java : 189
Not able to submit breakpoint LineBreakpoint RefreshThread.java : 188, reason: No executable location available at line 188 in class com.alexhulbert.icewind.gui.RefreshThread.
Invalid LineBreakpoint RefreshThread.java : 188
Not able to submit breakpoint LineBreakpoint RefreshThread.java : 187, reason: No executable location available at line 187 in class com.alexhulbert.icewind.gui.RefreshThread.
Invalid LineBreakpoint RefreshThread.java : 187
LineBreakpoint RefreshThread.java : 185 successfully submitted.
LineBreakpoint RefreshThread.java : 104 successfully submitted.
LineBreakpoint RefreshThread.java : 97 successfully submitted.
LineBreakpoint RefreshThread.java : 95 successfully submitted.
LineBreakpoint RefreshThread.java : 179 successfully submitted.
LineBreakpoint RefreshThread.java : 164 successfully submitted.
LineBreakpoint RefreshThread.java : 149 successfully submitted.
LineBreakpoint RefreshThread.java : 94 successfully submitted.
Breakpoint hit at line 94 in class com.alexhulbert.icewind.gui.RefreshThread by thread Thread-6.
Thread Thread-6 stopped at RefreshThread.java:94.
User program running
LineBreakpoint Wrapper.java : 36 successfully submitted.
LineBreakpoint Lockdown.java : 18 successfully submitted.
LineBreakpoint Lockdown.java : 16 successfully submitted.
LineBreakpoint Lockdown.java : 17 successfully submitted.
Breakpoint hit at line 16 in class com.alexhulbert.jmobiledevice.Lockdown by thread Thread-6.
Thread Thread-6 stopped at Lockdown.java:16.
User program running
Breakpoint hit at line 17 in class com.alexhulbert.jmobiledevice.Lockdown by thread Thread-6.
Thread Thread-6 stopped at Lockdown.java:17.
User program running
LineBreakpoint Pymobiledevice.java : 43 successfully submitted.
LineBreakpoint Pymobiledevice.java : 82 successfully submitted.
Not able to submit breakpoint LineBreakpoint Pymobiledevice.java : 69, reason: No executable location available at line 69 in class com.alexhulbert.jmobiledevice.Pymobiledevice.
Invalid LineBreakpoint Pymobiledevice.java : 69
Not able to submit breakpoint LineBreakpoint Pymobiledevice.java : 26, reason: No executable location available at line 26 in class com.alexhulbert.jmobiledevice.Pymobiledevice.
Invalid LineBreakpoint Pymobiledevice.java : 26
Not able to submit breakpoint LineBreakpoint Pymobiledevice.java : 41, reason: No executable location available at line 41 in class com.alexhulbert.jmobiledevice.Pymobiledevice.
Invalid LineBreakpoint Pymobiledevice.java : 41
Not able to submit breakpoint LineBreakpoint Pymobiledevice.java : 80, reason: No executable location available at line 80 in class com.alexhulbert.jmobiledevice.Pymobiledevice.
Invalid LineBreakpoint Pymobiledevice.java : 80
Not able to submit breakpoint LineBreakpoint Pymobiledevice.java : 79, reason: No executable location available at line 79 in class com.alexhulbert.jmobiledevice.Pymobiledevice.
Invalid LineBreakpoint Pymobiledevice.java : 79
Breakpoint hit at line 43 in class com.alexhulbert.jmobiledevice.Pymobiledevice by thread Thread-6.
Thread Thread-6 stopped at Pymobiledevice.java:43.
User program running
LineBreakpoint Extractor.java : 41 successfully submitted.
Breakpoint hit at line 41 in class com.alexhulbert.jmobiledevice.Extractor by thread Thread-6.
Thread Thread-6 stopped at Extractor.java:41.
User program running
Breakpoint hit at line 82 in class com.alexhulbert.jmobiledevice.Pymobiledevice by thread Thread-6.
Thread Thread-6 stopped at Pymobiledevice.java:82.
User program running
Breakpoint hit at line 18 in class com.alexhulbert.jmobiledevice.Lockdown by thread MainThread.
Thread MainThread stopped at Lockdown.java:18.
User program running
Breakpoint hit at line 95 in class com.alexhulbert.icewind.gui.RefreshThread by thread MainThread.
Thread MainThread stopped at RefreshThread.java:95.
User program running
Breakpoint hit at line 104 in class com.alexhulbert.icewind.gui.RefreshThread by thread MainThread.
Thread MainThread stopped at RefreshThread.java:104.
User program running
LineBreakpoint AuthenticateController.java : 60 successfully submitted.
LineBreakpoint AuthenticateController.java : 40 successfully submitted.
LineBreakpoint AuthenticateController.java : 43 successfully submitted.
LineBreakpoint AuthenticateController.java : 39 successfully submitted.
Breakpoint hit at line 39 in class com.alexhulbert.icewind.gui.AuthenticateController by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at AuthenticateController.java:39.
User program running
Breakpoint hit at line 40 in class com.alexhulbert.icewind.gui.AuthenticateController by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at AuthenticateController.java:40.
User program running
Breakpoint hit at line 43 in class com.alexhulbert.icewind.gui.AuthenticateController by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at AuthenticateController.java:43.
User program running
LineBreakpoint iCloud.java : 117 successfully submitted.
LineBreakpoint iCloud.java : 190 successfully submitted.
LineBreakpoint iCloud.java : 173 successfully submitted.
LineBreakpoint iCloud.java : 296 successfully submitted.
LineBreakpoint iCloud.java : 272 successfully submitted.
LineBreakpoint iCloud.java : 191 successfully submitted.
LineBreakpoint iCloud.java : 37 successfully submitted.
LineBreakpoint iCloud.java : 303 successfully submitted.
LineBreakpoint iCloud.java : 237 successfully submitted.
LineBreakpoint iCloud.java : 212 successfully submitted.
LineBreakpoint iCloud.java : 144 successfully submitted.
LineBreakpoint iCloud.java : 114 successfully submitted.
LineBreakpoint iCloud.java : 51 successfully submitted.
LineBreakpoint iCloud.java : 38 successfully submitted.
LineBreakpoint iCloud.java : 33 successfully submitted.
LineBreakpoint iCloud.java : 32 successfully submitted.
Breakpoint hit at line 32 in class com.alexhulbert.icewind.iCloud by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at iCloud.java:32.
User program running
Breakpoint hit at line 33 in class com.alexhulbert.icewind.iCloud by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at iCloud.java:33.
User program running
Breakpoint hit at line 114 in class com.alexhulbert.icewind.iCloud by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at iCloud.java:114.
User program running
Breakpoint hit at line 117 in class com.alexhulbert.icewind.iCloud by thread JavaFX Application Thread.
Thread JavaFX Application Thread stopped at iCloud.java:117.
User program running

**Comment by alexhulbert** [comment]
You just accidentally added some code breakpoints. Again, you're not going to be able to do anything with Icew1nd because it's incomplete.

**Comment by KJY5713** [comment]
how can i run this files?
